In [703]:
df =  pd.read_csv(r'C:\Users\Nisha.Nath\Documents\Talent\Data.csv')


In [704]:
df.columns

Index(['OfferId', 'OverallStatus', 'Status', 'Hiretype', 'RecruiterGPN',
       'Title', 'DateOfBirth', 'Original State', 'PinCode', 'Source',
       'Department', 'IT', 'Joining Center', 'Facility', 'Rank',
       'IsRotationalShift', 'NoticePeriod', 'Qualification1', 'Big four',
       'DAndI', 'hike%', 'JoiningBonus',
       'GoodsTransportationTravelEligibility', 'Stipend', 'Experienced',
       'IsNoticePeriodReimbursementProvided', 'ExpectedJoiningDate',
       'ActualJoiningDate'],
      dtype='object')

In [705]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3354 entries, 0 to 3353
Data columns (total 28 columns):
OfferId                                 3354 non-null int64
OverallStatus                           3354 non-null object
Status                                  3354 non-null object
Hiretype                                3354 non-null object
RecruiterGPN                            3354 non-null object
Title                                   3354 non-null object
DateOfBirth                             3354 non-null object
Original State                          3354 non-null object
PinCode                                 3354 non-null int64
Source                                  3354 non-null object
Department                              3354 non-null object
IT                                      3354 non-null int64
Joining Center                          3354 non-null object
Facility                                3354 non-null object
Rank                                    33

In [706]:
df.head()

OfferId OverallStatus         Status      Hiretype RecruiterGPN Title  \
0    20658        Joined  OfferAccepted  New Employee  XE020M42382    Mr   
1    21331        Joined  OfferAccepted  New Employee  XE020M42382    Mr   
2    21383        Joined  OfferAccepted  New Employee  XE020M39949    Mr   
3    21389        Joined  OfferAccepted  New Employee  XE020M42382    Ms   
4    21597        Joined  OfferAccepted  New Employee  XE021301732    Mr   

  DateOfBirth Original State  PinCode             Source  ... Big four  DAndI  \
0  15-11-1985      Karnataka   560016  EMPLOYEE REFERRAL  ...        1      0   
1  01-02-1981      Karnataka   560037             PORTAL  ...        0      0   
2  16-03-1990      Karnataka   560007  EMPLOYEE REFERRAL  ...        0      0   
3  09-07-1988      New Delhi   110018        CONSULTANCY  ...        1      0   
4  12-05-1987      Karnataka   560075  EMPLOYEE REFERRAL  ...        0      0   

  hike% JoiningBonus  GoodsTransportationTravelEligibility  Stipend  \
0   33%            0                                     0        0   
1   31%            0                                     0        0   
2   36%            0                                     0        0   
3   36%            0                                     0        0   
4   23%            0                                     0        0   

   Experienced IsNoticePeriodReimbursementProvided  ExpectedJoiningDate  \
0            1                                   0           02-07-2018   
1            1                                   0           30-07-2018   
2            1                                   0           16-07-2018   
3            1                                   1           16-07-2018   
4            1                                   0           30-07-2018   

   ActualJoiningDate  
0         02-07-2018  
1         30-07-2018  
2         16-07-2018  
3         16-07-2018  
4         30-07-2018  

[5 rows x 28 columns]

In [707]:
df.shape

(3354, 28)

In [708]:
df.size

93912

In [709]:
df.columns

Index(['OfferId', 'OverallStatus', 'Status', 'Hiretype', 'RecruiterGPN',
       'Title', 'DateOfBirth', 'Original State', 'PinCode', 'Source',
       'Department', 'IT', 'Joining Center', 'Facility', 'Rank',
       'IsRotationalShift', 'NoticePeriod', 'Qualification1', 'Big four',
       'DAndI', 'hike%', 'JoiningBonus',
       'GoodsTransportationTravelEligibility', 'Stipend', 'Experienced',
       'IsNoticePeriodReimbursementProvided', 'ExpectedJoiningDate',
       'ActualJoiningDate'],
      dtype='object')

In [710]:
df.dtypes

OfferId                                  int64
OverallStatus                           object
Status                                  object
Hiretype                                object
RecruiterGPN                            object
Title                                   object
DateOfBirth                             object
Original State                          object
PinCode                                  int64
Source                                  object
Department                              object
IT                                       int64
Joining Center                          object
Facility                                object
Rank                                     int64
IsRotationalShift                         bool
NoticePeriod                             int64
Qualification1                          object
Big four                                 int64
DAndI                                    int64
hike%                                   object
JoiningBonus 

In [711]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3354 entries, 0 to 3353
Data columns (total 28 columns):
OfferId                                 3354 non-null int64
OverallStatus                           3354 non-null object
Status                                  3354 non-null object
Hiretype                                3354 non-null object
RecruiterGPN                            3354 non-null object
Title                                   3354 non-null object
DateOfBirth                             3354 non-null object
Original State                          3354 non-null object
PinCode                                 3354 non-null int64
Source                                  3354 non-null object
Department                              3354 non-null object
IT                                      3354 non-null int64
Joining Center                          3354 non-null object
Facility                                3354 non-null object
Rank                                    33

In [712]:
df.describe()

OfferId       PinCode           IT         Rank  NoticePeriod  \
count   3354.000000  3.354000e+03  3354.000000  3354.000000   3354.000000   
mean   33832.187239  5.950064e+05     0.112105    40.369112      1.940072   
std     5310.642118  1.367584e+06     0.315543     9.811511      0.237390   
min    20658.000000  3.000000e+00     0.000000     4.000000      1.000000   
25%    28722.000000  5.600160e+05     0.000000    42.000000      2.000000   
50%    34893.500000  5.600640e+05     0.000000    44.000000      2.000000   
75%    38287.750000  5.831010e+05     0.000000    44.000000      2.000000   
max    44164.000000  4.521628e+07     1.000000    44.000000      2.000000   

          Big four        DAndI  JoiningBonus  \
count  3354.000000  3354.000000   3354.000000   
mean      0.234049     0.003876      0.013715   
std       0.423466     0.062146      0.116322   
min       0.000000     0.000000      0.000000   
25%       0.000000     0.000000      0.000000   
50%       0.000000     0.000000      0.000000   
75%       0.000000     0.000000      0.000000   
max       1.000000     1.000000      1.000000   

       GoodsTransportationTravelEligibility      Stipend  Experienced  
count                           3354.000000  3354.000000  3354.000000  
mean                               0.207215     0.063804     0.937090  
std                                0.405372     0.244441     0.242837  
min                                0.000000     0.000000     0.000000  
25%                                0.000000     0.000000     1.000000  
50%                                0.000000     0.000000     1.000000  
75%                                0.000000     0.000000     1.000000  
max                                1.000000     1.000000     1.000000

In [713]:
df.isnull().sum()

OfferId                                   0
OverallStatus                             0
Status                                    0
Hiretype                                  0
RecruiterGPN                              0
Title                                     0
DateOfBirth                               0
Original State                            0
PinCode                                   0
Source                                    0
Department                                0
IT                                        0
Joining Center                            0
Facility                                  0
Rank                                      0
IsRotationalShift                         0
NoticePeriod                              0
Qualification1                            0
Big four                                  0
DAndI                                     0
hike%                                     0
JoiningBonus                              0
GoodsTransportationTravelEligibi

In [714]:
df.dtypes

OfferId                                  int64
OverallStatus                           object
Status                                  object
Hiretype                                object
RecruiterGPN                            object
Title                                   object
DateOfBirth                             object
Original State                          object
PinCode                                  int64
Source                                  object
Department                              object
IT                                       int64
Joining Center                          object
Facility                                object
Rank                                     int64
IsRotationalShift                         bool
NoticePeriod                             int64
Qualification1                          object
Big four                                 int64
DAndI                                    int64
hike%                                   object
JoiningBonus 

In [715]:
df.OverallStatus.value_counts()

Joined           2665
OfferDeclined     689
Name: OverallStatus, dtype: int64

In [716]:
df = df.rename(columns = {'Original State':'Original_State'})

In [717]:
df = df.rename(columns = {'Joining Center':'Joining_Center'})

In [718]:
df = df.rename(columns = {'hike%':'Hike'})

In [719]:
df = df.rename(columns = {'Big four': 'Big_four'})

In [720]:
df.columns

Index(['OfferId', 'OverallStatus', 'Status', 'Hiretype', 'RecruiterGPN',
       'Title', 'DateOfBirth', 'Original_State', 'PinCode', 'Source',
       'Department', 'IT', 'Joining_Center', 'Facility', 'Rank',
       'IsRotationalShift', 'NoticePeriod', 'Qualification1', 'Big_four',
       'DAndI', 'Hike', 'JoiningBonus', 'GoodsTransportationTravelEligibility',
       'Stipend', 'Experienced', 'IsNoticePeriodReimbursementProvided',
       'ExpectedJoiningDate', 'ActualJoiningDate'],
      dtype='object')

In [721]:
df['Hike'] = df.Hike.str.replace('%', '')
df['Hike'] = df['Hike'].astype(str).astype(int)

In [722]:
df['Hike'].dtype

dtype('int32')

In [723]:
df.head(3)

OfferId OverallStatus         Status      Hiretype RecruiterGPN Title  \
0    20658        Joined  OfferAccepted  New Employee  XE020M42382    Mr   
1    21331        Joined  OfferAccepted  New Employee  XE020M42382    Mr   
2    21383        Joined  OfferAccepted  New Employee  XE020M39949    Mr   

  DateOfBirth Original_State  PinCode             Source  ... Big_four  DAndI  \
0  15-11-1985      Karnataka   560016  EMPLOYEE REFERRAL  ...        1      0   
1  01-02-1981      Karnataka   560037             PORTAL  ...        0      0   
2  16-03-1990      Karnataka   560007  EMPLOYEE REFERRAL  ...        0      0   

  Hike JoiningBonus  GoodsTransportationTravelEligibility  Stipend  \
0   33            0                                     0        0   
1   31            0                                     0        0   
2   36            0                                     0        0   

   Experienced IsNoticePeriodReimbursementProvided  ExpectedJoiningDate  \
0            1                                   0           02-07-2018   
1            1                                   0           30-07-2018   
2            1                                   0           16-07-2018   

   ActualJoiningDate  
0         02-07-2018  
1         30-07-2018  
2         16-07-2018  

[3 rows x 28 columns]

In [724]:
df['DOB_year'] = pd.DatetimeIndex(df['DateOfBirth']).year

In [725]:
df['Age'] = 2019 - df['DOB_year']

In [726]:
df_1 = df[['OverallStatus', 'Hiretype', 'RecruiterGPN',
       'Title', 'Age', 'Original_State', 'PinCode', 'Source',
       'Department', 'IT', 'Joining_Center', 'Facility', 'Rank',
       'IsRotationalShift', 'NoticePeriod', 'Qualification1','Hike', 'Big_four','JoiningBonus',
       'GoodsTransportationTravelEligibility', 'Stipend', 'Experienced',
       'IsNoticePeriodReimbursementProvided', 'ExpectedJoiningDate']]

In [727]:
df_1['Expected_Month'] = pd.DatetimeIndex(df['ExpectedJoiningDate']).month

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [728]:
df_1['IsNoticePeriodReimbursementProvided'] = df_1['IsNoticePeriodReimbursementProvided'].str.replace('True','1')
df_1['IsNoticePeriodReimbursementProvided'] = df_1['IsNoticePeriodReimbursementProvided'].str.replace('False','0')
df_1['IsNoticePeriodReimbursementProvided'] = df_1['IsNoticePeriodReimbursementProvided'].replace('nan', np.nan).fillna(0)

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a 

In [729]:
df_1[['IsNoticePeriodReimbursementProvided']] = df_1[['IsNoticePeriodReimbursementProvided']].apply(pd.to_numeric)

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\frame.py:3494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [730]:
df_1.IsNoticePeriodReimbursementProvided.value_counts()

0    3309
1      45
Name: IsNoticePeriodReimbursementProvided, dtype: int64

In [731]:
df_1.Expected_Month.value_counts()

1     551
10    361
4     346
3     287
11    275
7     269
6     269
5     260
12    227
2     217
8     197
9      95
Name: Expected_Month, dtype: int64

In [732]:
df_1.Experienced.value_counts()

1    3143
0     211
Name: Experienced, dtype: int64

In [733]:
df_1.Stipend.value_counts()

0    3140
1     214
Name: Stipend, dtype: int64

In [734]:
df_1.GoodsTransportationTravelEligibility.value_counts()

0    2659
1     695
Name: GoodsTransportationTravelEligibility, dtype: int64

In [735]:
df_1.JoiningBonus.value_counts()

0    3308
1      46
Name: JoiningBonus, dtype: int64

In [736]:
df_1.Hike.value_counts()

 100    1304
 0       215
 23      122
 24      111
 26       91
        ... 
-15        1
 61        1
 67        1
 69        1
 74        1
Name: Hike, Length: 74, dtype: int64

In [737]:
df_1.Qualification1.value_counts()

Post Grad    2674
Grad          449
MBA           217
CA             14
Name: Qualification1, dtype: int64

In [738]:
df_1.NoticePeriod.value_counts()

2    3153
1     201
Name: NoticePeriod, dtype: int64

In [739]:
df_1.IsRotationalShift.value_counts()

False    3296
True       58
Name: IsRotationalShift, dtype: int64

In [740]:
df_1.Rank.value_counts()

44    2010
42     997
4      215
32     132
Name: Rank, dtype: int64

In [741]:
df_1.Facility.value_counts()

BLR CORAL/EYGDS/SEZ               2649
GGN UCP/All Entities/Non-SEZ       239
CHN DLF/EYLLP/EYGDS/SEZ            135
KOC Carnival/EYGDS/SEZ-SFT         116
CHN DLF/ EYGDS/SEZ-SFT              78
KOC Carnival4/All Entities/SEZ      44
KOC Carnival2/All Entities/SEZ      42
BLR RMZ/All Entities/NON-SEZ        25
TVM Thejaswini/All/NON-SEZ           8
TVM Drishya/All Entities/SEZ         8
BLR Garnet/EYLLP/EYGDS/SEZ           6
BLR BMP/All Entities/NON-SEZ         2
KOC Athulya/EYGBS/SEZ                1
BLR BTP/All Entities/NON-SEZ         1
Name: Facility, dtype: int64

In [742]:
df_1.IT.value_counts()

0    2978
1     376
Name: IT, dtype: int64

In [743]:
df_1.Joining_Center.value_counts()

Bangalore     2683
Gurgaon        239
Chennai        213
Kochi          203
Trivandrum      16
Name: Joining_Center, dtype: int64

In [744]:
df_1.PinCode.value_counts()

560037    122
560043     98
560016     91
560076     53
560078     49
         ... 
600074      1
600072      1
3           1
600062      1
700020      1
Name: PinCode, Length: 1019, dtype: int64

In [745]:
df_1.Source.value_counts()

EMPLOYEE REFERRAL        1294
PORTAL                    765
CONSULTANCY               733
CAMPUS                    412
WALK-IN                    50
GDS LEAP                   48
CWR TO FTE CONVERSION      23
ALTERNATE SOURCE           15
OFF CAMPUS                  7
TRANSFER                    5
OTHER TRANSFER              1
ADVERTISEMENT               1
Name: Source, dtype: int64

In [746]:
df_1.Hiretype.value_counts()

New Employee    3022
Re hire          264
Transfer          68
Name: Hiretype, dtype: int64

In [747]:
df_1.RecruiterGPN.value_counts()

XE020M38015    599
XE020M42382    560
XE020M32824    443
XE020M39949    316
XE020M24041    315
XE020M36003    254
XE020M51545    152
XE020M63277    116
XE020M32654    116
XE020M22317    110
XE021306642     79
XE020M17867     74
XE020M24506     62
XE020M00201     59
XE021305129     53
XE020M63244     35
XE021301732      6
XE021306728      2
XE020M20654      1
IN010M41415      1
XE021305189      1
Name: RecruiterGPN, dtype: int64

In [748]:
df_1.Title.value_counts()

Mr    1751
Ms    1603
Name: Title, dtype: int64

In [749]:
df_1.Age.value_counts()

24    383
23    311
25    309
27    282
26    276
22    261
28    255
30    218
29    217
31    151
32    138
21    105
33    104
34     59
35     56
36     44
20     38
37     33
40     24
38     23
41     17
42     13
39     12
43      9
44      6
45      4
19      3
46      1
50      1
48      1
Name: Age, dtype: int64

In [750]:
df_1.Original_State.value_counts()

Karnataka            1959
Tamil Nadu            310
Kerala                293
Andhra Pradesh        178
West Bengal           171
New Delhi             126
Haryana                86
Maharashtra            61
Uttar Pradesh          49
Telangana              49
Jharkhand              16
Gujarat                13
Orissa                  9
Uttarakhand             8
Assam                   6
Madhya Pradesh          6
Rajasthan               4
Chhattisgarh            2
Punjab                  2
England                 1
Jammu and Kashmir       1
Australia               1
Georgia                 1
HARYANA                 1
Sharjah                 1
Name: Original_State, dtype: int64

In [751]:
df_1['OverallStatus_Labelenc'] = df["OverallStatus"].values
print("BEFORE ENCODING : {}".format(df_1.OverallStatus_Labelenc[0:10]))

print("")

le = preprocessing.LabelEncoder()
le.fit(df_1.OverallStatus)

print("ENCODED CLASSES : {}".format(le.classes_))
print("")

df_1['OverallStatus_Labelenc'] = le.transform(df.OverallStatus)

print(df_1.OverallStatus_Labelenc.value_counts())
print(df.OverallStatus.value_counts())

BEFORE ENCODING : 0    Joined
1    Joined
2    Joined
3    Joined
4    Joined
5    Joined
6    Joined
7    Joined
8    Joined
9    Joined
Name: OverallStatus_Labelenc, dtype: object

ENCODED CLASSES : ['Joined' 'OfferDeclined']

0    2665
1     689
Name: OverallStatus_Labelenc, dtype: int64
Joined           2665
OfferDeclined     689
Name: OverallStatus, dtype: int64


c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [752]:
#df['Hike'] = df['Hike'].astype(int64)
df['Hike'] = df['Hike'].astype(int)

In [753]:
df.columns

Index(['OfferId', 'OverallStatus', 'Status', 'Hiretype', 'RecruiterGPN',
       'Title', 'DateOfBirth', 'Original_State', 'PinCode', 'Source',
       'Department', 'IT', 'Joining_Center', 'Facility', 'Rank',
       'IsRotationalShift', 'NoticePeriod', 'Qualification1', 'Big_four',
       'DAndI', 'Hike', 'JoiningBonus', 'GoodsTransportationTravelEligibility',
       'Stipend', 'Experienced', 'IsNoticePeriodReimbursementProvided',
       'ExpectedJoiningDate', 'ActualJoiningDate', 'DOB_year', 'Age'],
      dtype='object')

In [754]:
df_1.columns

Index(['OverallStatus', 'Hiretype', 'RecruiterGPN', 'Title', 'Age',
       'Original_State', 'PinCode', 'Source', 'Department', 'IT',
       'Joining_Center', 'Facility', 'Rank', 'IsRotationalShift',
       'NoticePeriod', 'Qualification1', 'Hike', 'Big_four', 'JoiningBonus',
       'GoodsTransportationTravelEligibility', 'Stipend', 'Experienced',
       'IsNoticePeriodReimbursementProvided', 'ExpectedJoiningDate',
       'Expected_Month', 'OverallStatus_Labelenc'],
      dtype='object')

In [755]:
df_1 = df_1[['OverallStatus_Labelenc','Hiretype', 'RecruiterGPN',
       'Title', 'Age', 'Original_State', 'PinCode', 'Source',
       'Department', 'IT', 'Joining_Center', 'Facility', 'Rank','Big_four',
       'IsRotationalShift', 'NoticePeriod', 'Qualification1','Hike', 'JoiningBonus',
       'GoodsTransportationTravelEligibility', 'Stipend', 'Experienced',
       'IsNoticePeriodReimbursementProvided', 'Expected_Month']]

In [756]:
df_1.dtypes

OverallStatus_Labelenc                   int32
Hiretype                                object
RecruiterGPN                            object
Title                                   object
Age                                      int64
Original_State                          object
PinCode                                  int64
Source                                  object
Department                              object
IT                                       int64
Joining_Center                          object
Facility                                object
Rank                                     int64
Big_four                                 int64
IsRotationalShift                         bool
NoticePeriod                             int64
Qualification1                          object
Hike                                     int32
JoiningBonus                             int64
GoodsTransportationTravelEligibility     int64
Stipend                                  int64
Experienced  

In [934]:
X = df_1[['Hiretype','Title', 'Age', 'Source', 'IT', 'Joining_Center','RecruiterGPN', 'Rank', 'NoticePeriod','Big_four','Qualification1','Hike', 'Experienced','Expected_Month','IsNoticePeriodReimbursementProvided']]

In [935]:
X.dtypes

Hiretype                               object
Title                                  object
Age                                     int64
Source                                 object
IT                                      int64
Joining_Center                         object
RecruiterGPN                           object
Rank                                    int64
NoticePeriod                            int64
Big_four                                int64
Qualification1                         object
Hike                                    int32
Experienced                             int64
Expected_Month                          int64
IsNoticePeriodReimbursementProvided     int64
dtype: object

In [936]:
X.isnull().sum()

Hiretype                               0
Title                                  0
Age                                    0
Source                                 0
IT                                     0
Joining_Center                         0
RecruiterGPN                           0
Rank                                   0
NoticePeriod                           0
Big_four                               0
Qualification1                         0
Hike                                   0
Experienced                            0
Expected_Month                         0
IsNoticePeriodReimbursementProvided    0
dtype: int64

In [937]:
y = df_1[['OverallStatus_Labelenc']]

In [938]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import make_column_transformer
from sklearn.metrics import confusion_matrix
numColList=(X.dtypes[(X.dtypes=="int64") | (X.dtypes=="int")]).index
strColList=X.dtypes[X.dtypes=="object"].index
enc=make_column_transformer(
    (MinMaxScaler(), numColList),
    (OneHotEncoder(),strColList))
X_transform=enc.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_transform, y, random_state=0)

In [939]:
strColList

Index(['Hiretype', 'Title', 'Source', 'Joining_Center', 'RecruiterGPN',
       'Qualification1'],
      dtype='object')

In [940]:
numColList

Index(['Age', 'IT', 'Rank', 'NoticePeriod', 'Big_four', 'Hike', 'Experienced',
       'Expected_Month', 'IsNoticePeriodReimbursementProvided'],
      dtype='object')

In [941]:
X_train.shape

(2515, 56)

In [942]:
y_train.shape

(2515, 1)

In [943]:
y_test.OverallStatus_Labelenc.value_counts()

0    655
1    184
Name: OverallStatus_Labelenc, dtype: int64

In [944]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import recall_score
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.pipeline import Pipeline
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import GridSearchCV
#from adspy_shared_utilities import plot_class_regions_for_classifier_subplot

#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

clf = GradientBoostingClassifier(max_depth=2, n_estimators=1000, learning_rate =0.1).fit(X_train, y_train)
prediction_on_testData=clf.predict(X_test)
print("Test Accuracy", clf.score(X_test,y_test))
confusion_matrix(y_test,prediction_on_testData)

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Test Accuracy 0.7771156138259833


array([[619,  36],
       [151,  33]], dtype=int64)

In [945]:
print(metrics.recall_score(y_test,prediction_on_testData, average = None))

[0.94503817 0.17934783]


In [807]:
pipe = Pipeline(steps=[('estimator', GradientBoostingClassifier())])

parameters = [{
    'estimator__n_estimators': (5,10,20,30,40,50,60,70,80,90),
    'estimator__learning_rate': [0.01,0.03,0.05,.07,0.09,0.1,0.2,.3,.4,.5,1],
    'estimator__max_depth':(10,20,30,40,50,60,70,80,90),
}]

grid_search_tune = GridSearchCV(pipe, parameters, cv=2, n_jobs=5, verbose=3)
grid_search_tune.fit(X_train, y_train)
print(grid_search_tune.score(X_train,y_train))

print("Best parameters set:")
print(grid_search_tune.best_estimator_.steps)


Fitting 2 folds for each of 990 candidates, totalling 1980 fits


[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done  22 tasks      | elapsed:   20.8s
[Parallel(n_jobs=5)]: Done 118 tasks      | elapsed:  1.5min
[Parallel(n_jobs=5)]: Done 278 tasks      | elapsed:  3.4min
[Parallel(n_jobs=5)]: Done 502 tasks      | elapsed:  6.2min
[Parallel(n_jobs=5)]: Done 790 tasks      | elapsed:  9.5min
[Parallel(n_jobs=5)]: Done 1142 tasks      | elapsed: 13.4min
[Parallel(n_jobs=5)]: Done 1558 tasks      | elapsed: 17.4min
[Parallel(n_jobs=5)]: Done 1980 out of 1980 | elapsed: 21.1min finished
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7992047713717694
Best parameters set:
[('estimator', GradientBoostingClassifier(learning_rate=0.01, max_depth=10, n_estimators=5))]


In [946]:
clf = GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=10,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=5,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False).fit(X_train, y_train)
#prediction_on_testData=clf.predict(X_test)
clf.fit(X_train,y_train)
prob_predict = clf.predict(X_test)
print("Test Accuracy", clf.score(X_test,y_test))
print(confusion_matrix(y_test,prediction_on_testData))
print(metrics.recall_score(y_test,prediction_on_testData, average = None))

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Test Accuracy 0.7806912991656734
[[619  36]
 [151  33]]
[0.94503817 0.17934783]


In [836]:
X_train

array([[0.16129032, 0.        , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.19354839, 0.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.16129032, 0.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.41935484, 0.        , 0.95      , ..., 0.        , 0.        ,
        1.        ],
       [0.16129032, 0.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.4516129 , 1.        , 0.95      , ..., 0.        , 0.        ,
        1.        ]])

In [837]:
y_train = y_train.to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [838]:
cross_val_score(clf, X_train, y_train, scoring='recall', cv=10) 

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [374]:
?GradientBoostingClassifier

In [144]:
Proba_pre = clf.predict_proba(X_test)

In [147]:
df_proba = pd.DataFrame(Proba_pre)

In [154]:
y_test

OverallStatus_Labelenc
3256                       0
1808                       1
3338                       0
1318                       0
1128                       0
...                      ...
2784                       0
2426                       0
1363                       0
3234                       0
778                        1

[839 rows x 1 columns]

In [158]:
pd.concat([y_test, df_proba], axis=1)

OverallStatus_Labelenc         0         1
0                        NaN  0.864315  0.135685
1                        0.0  0.828406  0.171594
2                        NaN  0.846220  0.153780
3                        NaN  0.828406  0.171594
4                        0.0  0.843780  0.156220
...                      ...       ...       ...
3341                     0.0       NaN       NaN
3345                     0.0       NaN       NaN
3349                     0.0       NaN       NaN
3352                     0.0       NaN       NaN
3353                     0.0       NaN       NaN

[1462 rows x 3 columns]

In [947]:
clf = GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.09, loss='deviance', max_depth=10,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=5,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False).fit(X_train, y_train)
prediction_on_testData=clf.predict(X_test)
print("Test Accuracy", clf.score(X_test,y_test))
confusion_matrix(prediction_on_testData,y_test)
metrics.recall_score(y_test,prediction_on_testData,average = None)

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Test Accuracy 0.7723480333730631


array([0.98015267, 0.0326087 ])

In [948]:
from sklearn.ensemble import RandomForestClassifier
rand_classifer = RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=100,class_weight={0:.40,1:.6},random_state=0)
rand_classifer.fit(X_train,y_train)
y_pred_randforest = rand_classifer.predict(X_test)
print(metrics.confusion_matrix(y_test,y_pred_randforest))
print(metrics.recall_score(y_test,y_pred_randforest, average = None))
print(metrics.accuracy_score(y_test,y_pred_randforest))

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[611  44]
 [148  36]]
[0.93282443 0.19565217]
0.7711561382598331


In [821]:
?RandomForestClassifier

In [554]:
y_test.OverallStatus_Labelenc.value_counts()

Joined           655
OfferDeclined    184
Name: OverallStatus_Labelenc, dtype: int64

In [139]:
?LogisticRegression

In [365]:
from sklearn.preprocessing import binarize
from sklearn.metrics import accuracy_score, roc_auc_score, auc
 
t = 0.4  #threshold
proba = clf.predict_proba(X_test)
pred_at_t = binarize(proba, t)[:,1]

print(metrics.confusion_matrix(y_test,pred_at_t))
print(metrics.recall_score(y_test,pred_at_t,average = None))

[[640  15]
 [164  20]]
[0.97709924 0.10869565]


In [950]:
y_test = y_test.to_numpy()

In [951]:
y_test

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [952]:
from sklearn.preprocessing import binarize
from sklearn.metrics import accuracy_score, roc_auc_score, auc
 
t = 0.3  #threshold
proba = clf.predict_proba(X_test)
pred_at_t = binarize(proba, t)[:,1]

print(metrics.confusion_matrix(y_test,pred_at_t))
print(metrics.recall_score(y_test,pred_at_t,average = None))

[[578  77]
 [134  50]]
[0.88244275 0.27173913]


In [400]:
type(y_train)


pandas.core.frame.DataFrame

In [407]:
X_train

<2515x187 sparse matrix of type '<class 'numpy.float64'>'
	with 40986 stored elements in Compressed Sparse Row format>

In [391]:
clf

GradientBoostingClassifier(learning_rate=0.01, max_depth=10, n_estimators=5)

In [953]:
from sklearn.preprocessing import binarize
from sklearn.metrics import accuracy_score, roc_auc_score, auc
 
t = 0.2  #threshold

clf.fit(X_train,y_train)
proba = clf.predict_proba(X_test)
pred_at_t = binarize(proba, t)[:,1]
cv_new = cross_val_score(clf, X_train, y_train,cv=10, scoring='recall')
print(cv_new)
print(np.mean(cv_new))
print(np.std(cv_new))
print(metrics.confusion_matrix(y_test,pred_at_t))
print(metrics.recall_score(y_test,pred_at_t,average = None))

c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\nisha.nath\appdata\local\programs\python\python37-32

[0.03921569 0.01960784 0.01960784 0.1372549  0.03921569 0.06
 0.02       0.02       0.04       0.08      ]
0.04749019607843137
0.03539829939635218
[[493 162]
 [ 94  90]]
[0.75267176 0.48913043]


In [423]:
X_train.shape

(2515, 187)

In [954]:
from sklearn.preprocessing import binarize
from sklearn.metrics import accuracy_score, roc_auc_score, auc
 
t = 0.25  #threshold
proba = clf.predict_proba(X_test)
pred_at_t = binarize(proba, t)[:,1]

print(metrics.confusion_matrix(y_test,pred_at_t))
print(metrics.recall_score(y_test,pred_at_t,average = None))

[[545 110]
 [119  65]]
[0.83206107 0.35326087]


In [808]:
#Crossvalidation
#models = [
 #   GradientBoostingClassifier(n_estimators=200, random_state=0)],
#CV = 10
#cv_df = pd.DataFrame(index=range(CV * len(models)))
#entries = []
#re = []
#pre = []
#for model in models:
   # model_name = model.__class__.__name__
   # accuracies = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=CV)
   # recalls = cross_val_score(model, X_train, y_train, scoring='recall', cv=CV,)

In [ ]:
#cv_df_precision = pd.DataFrame(pre, columns=['model_name', 'fold_idx', 'precision_score']) 
#cv_df_recall = pd.DataFrame(re, columns=['model_name', 'fold_idx', 'recall_score']) 
#import seaborn as sns
#import matplotlib.pyplot as plt

#plt.figure(figsize=(10,5))
#sns.boxplot(x='model_name', y='accuracy', data=cv_df).set_title("Accuracy comparison - Cross Validation")
#sns.stripplot(x='model_name', y='accuracy', data=cv_df, 
#              size=8, jitter=True, edgecolor="gray", linewidth=2)
#plt.show() 
#import seaborn as sns
#import matplotlib.pyplot as plt

#plt.figure(figsize=(10,5))
#sns.boxplot(x='model_name', y='precision_score', data=cv_df_precision).set_title("Precision comparison - Cross Validation")
#sns.stripplot(x='model_name', y='precision_score', data=cv_df_precision, 
#              size=8, jitter=True, edgecolor="gray", linewidth=2)
#plt.show() 
#import seaborn as sns
##import matplotlib.pyplot as plt

#plt.figure(figsize=(10,5))
#sns.boxplot(x='model_name', y='recall_score', data=cv_df_recall).set_title("Recall scores - Cross Validation")
#sns.stripplot(x='model_name', y='recall_score', data=cv_df_recall, 
#              size=8, jitter=True, edgecolor="gray", linewidth=2)
#plt.show() 
 
